### ISSUE TITLE
Cannot run `./validate` on linux

### ISSUE THREAD

**Issue by bwasmith** [cloudfoundry/slack-interrupt-bot#4]
This is probably to be expected. I imagine this should only run on OSX?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

# With a clean version of Master
$ ./validate
./validate: line 22: /home/pivotal/workspace/cloudfoundry-slack-interrupt-bot/tmp/delegatebot-0.1.0/delegatebot: cannot execute binary file: Exec format error
```

**Comment by bwasmith** [comment]
@acrmp This was the error I was seeing on my end.

**Comment by dpb587** [comment]
Yeah, I have a nice, [unhelpful `TODO`](https://github.com/dpb587/cloudfoundry-slack-interrupt-bot/blob/master/validate#L15) for that. If you have a simple one-liner to detect OS, PRs are nice :)

Otherwise I might just end up being lazy and do `go env GOOS` at some point, assuming `go`.

**Comment by bwasmith** [comment]
Lol

I consider poking around it a bit. Thanks for this Interrupt Bot! It seems great so far

**Comment by dpb587-pivotal** [comment]
Closing - no longer needed since ede767c011a6b71d05ea132780257ebb175c9c58.
